import jsdocEslintConfig from 'eslint-plugin-jsdoc'

/** @type {import('eslint').Linter.Config[]} */
export const jsdocs = [
  jsdocEslintConfig.configs['flat/recommended'],
  {
    name: 'padcom/flat/jsdocs',
    files: ['**/*.[j,mj,cj,t,mt]s', '**/*.[j,t]sx', '**/*.vue'],
    rules: {
      'jsdoc/check-access': 'error',
      'jsdoc/check-alignment': 'error',
      // TODO: Rain check
      'jsdoc/check-examples': 'off',
      'jsdoc/check-indentation': 'error',
      'jsdoc/check-line-alignment': 'off',
      'jsdoc/check-param-names': 'error',
      'jsdoc/check-property-names': 'error',
      'jsdoc/check-syntax': 'off',
      'jsdoc/check-tag-names': 'error',
      'jsdoc/check-template-names': 'off',
      'jsdoc/check-types': 'error',
      'jsdoc/check-values': 'error',
      'jsdoc/convert-to-jsdoc-comments': 'off',
      'jsdoc/empty-tags': 'error',
      'jsdoc/implements-on-classes': 'error',
      'jsdoc/imports-as-dependencies': 'off',
      'jsdoc/informative-docs': 'off',
      'jsdoc/lines-before-block': 'off',
      'jsdoc/match-description': 'off',
      'jsdoc/match-name': 'off',
      'jsdoc/multiline-blocks': 'error',
      'jsdoc/no-bad-blocks': 'off',
      'jsdoc/no-blank-block-descriptions': 'off',
      'jsdoc/no-blank-blocks': 'off',
      'jsdoc/no-defaults': 'error',
      'jsdoc/no-missing-syntax': 'off',
      'jsdoc/no-multi-asterisks': 'error',
      'jsdoc/no-restricted-syntax': 'off',
      'jsdoc/no-types': 'off',
      'jsdoc/no-undefined-types': 'error',
      'jsdoc/require-asterisk-prefix': 'off',
      'jsdoc/require-description-complete-sentence': 'off',
      'jsdoc/require-description': ['error', { descriptionStyle: 'body' }],
      'jsdoc/require-example': 'off',
      'jsdoc/require-file-overview': 'off',
      'jsdoc/require-hyphen-before-param-description': 'off',
      'jsdoc/require-jsdoc': ['error', {
        contexts: ['TSInterfaceDeclaration', 'TSMethodSignature', 'TSPropertySignature'],
        publicOnly: true,
      }],
      'jsdoc/require-param-description': 'error',
      'jsdoc/require-param-name': 'error',
      'jsdoc/require-param-type': 'error',
      'jsdoc/require-param': 'error',
      'jsdoc/require-property-description': 'error',
      'jsdoc/require-property-name': 'error',
      'jsdoc/require-property-type': 'error',
      'jsdoc/require-property': 'error',
      'jsdoc/require-returns-check': 'error',
      'jsdoc/require-returns-description': 'error',
      'jsdoc/require-returns-type': 'error',
      'jsdoc/require-returns': 'error',
      'jsdoc/require-template': 'off',
      'jsdoc/require-throws': 'off',
      'jsdoc/require-yields-check': 'error',
      'jsdoc/require-yields': 'error',
      'jsdoc/sort-tags': 'off',
      'jsdoc/tag-lines': ['error', 'never', { startLines: 1 }],
      'jsdoc/text-escaping': 'off',
      'jsdoc/valid-types': 'error',
    },
  },
  {
    name: 'padcom/flat/jsdocs-ts-overrides',
    files: ['**/*.[t,mt]s', '**/*.[tsx', '**/*.vue'],
    rules: {
      'jsdoc/check-tag-names': ['error', { typed: true }],
      'jsdoc/no-types': 'error',
      'jsdoc/require-param-type': 'off',
      'jsdoc/require-property-type': 'off',
      'jsdoc/require-returns-type': 'off',
    },
  },
]
